package com.example.implementingserversidekotlindevelopment

import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest
class ImplementingServerSideKotlinDevelopmentApplicationTests
